from socket import *
from select import select


serverPort = 8080
serverSocket = socket(AF_INET, SOCK_STREAM)
serverSocket.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
serverSocket.bind(('', serverPort))
serverSocket.listen(1)
print 'The server is ready to receive'
eventSourceList = [serverSocket]

#start the server with a certain behavior
def runServer(behavior):
    try:
        while 1:
            (readList, writeList, errorList)   = select(eventSourceList, [], [])
            for descriptor in readList:
                # if the event was generated by a new connection
                if descriptor == serverSocket:
                    connectionSocket, addr = serverSocket.accept()
                    eventSourceList.append(connectionSocket)
                    print 'New connection ',addr
                else:
                    connectionSocket = descriptor
                    data = connectionSocket.recv(1024)
                    # if the event was generated by data received
                    if data != '':
                        print 'Received new data on port:', addr
                        print data
                        print
                        response = behavior(data)
                        print response
                        connectionSocket.send(response) 
                    # if the event was generated by connection closed
                    else:
                        print 'Client ', addr, ' closed socket'
                        print 'Closing connection socket'
                        connectionSocket.close()
                        eventSourceList.remove(connectionSocket)
    finally:
        serverSocket.close()
